#%RAML 1.0 DataType

type: object
properties:
  customerId:
    type: string
    required: true
    example: "4d4de7d6-7f5e-4778-9c70-babba6c25c55"
    description: Unique Id of the customer.
  message:
    type: string
    required: true
    example: "Customer created successfully"
    description: Status of the backend operation.
  